<?php
declare(strict_types=1);

// ApiTools SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

ApiToolsUtility::setRegistrar(function (ApiToolsUtility $u): void {
    $u->clean = [ApiToolsClean::class, 'call'];
    $u->done = [ApiToolsDone::class, 'call'];
    $u->make_error = [ApiToolsMakeError::class, 'call'];
    $u->feature_add = [ApiToolsFeatureAdd::class, 'call'];
    $u->feature_hook = [ApiToolsFeatureHook::class, 'call'];
    $u->feature_init = [ApiToolsFeatureInit::class, 'call'];
    $u->fetcher = [ApiToolsFetcher::class, 'call'];
    $u->make_fetch_def = [ApiToolsMakeFetchDef::class, 'call'];
    $u->make_context = [ApiToolsMakeContext::class, 'call'];
    $u->make_options = [ApiToolsMakeOptions::class, 'call'];
    $u->make_request = [ApiToolsMakeRequest::class, 'call'];
    $u->make_response = [ApiToolsMakeResponse::class, 'call'];
    $u->make_result = [ApiToolsMakeResult::class, 'call'];
    $u->make_point = [ApiToolsMakePoint::class, 'call'];
    $u->make_spec = [ApiToolsMakeSpec::class, 'call'];
    $u->make_url = [ApiToolsMakeUrl::class, 'call'];
    $u->param = [ApiToolsParam::class, 'call'];
    $u->prepare_auth = [ApiToolsPrepareAuth::class, 'call'];
    $u->prepare_body = [ApiToolsPrepareBody::class, 'call'];
    $u->prepare_headers = [ApiToolsPrepareHeaders::class, 'call'];
    $u->prepare_method = [ApiToolsPrepareMethod::class, 'call'];
    $u->prepare_params = [ApiToolsPrepareParams::class, 'call'];
    $u->prepare_path = [ApiToolsPreparePath::class, 'call'];
    $u->prepare_query = [ApiToolsPrepareQuery::class, 'call'];
    $u->graphql_body = [ApiToolsGraphql::class, 'body'];
    $u->graphql_errors = [ApiToolsGraphql::class, 'errors'];
    $u->result_basic = [ApiToolsResultBasic::class, 'call'];
    $u->result_body = [ApiToolsResultBody::class, 'call'];
    $u->result_headers = [ApiToolsResultHeaders::class, 'call'];
    $u->transform_request = [ApiToolsTransformRequest::class, 'call'];
    $u->transform_response = [ApiToolsTransformResponse::class, 'call'];
});
